# ----------- CONFIGURABLE START -----------
title:            "Think out loud"
description:      "A Charles Blog"
url:              #
signoff:          "Charles"
#facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
#google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
#share:            false # Turn on twitter and facebook share buttons

links:
#  - name:         About
#    url:          /about
  - name:         Blog
    url:          /index.html
  - name:         Email
    url:          mailto:dodoinblue@gmail.com
    external:     true
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title

defaults:
  - values:
      layout: "default"