title:            Think aloud
description:      A Charles blog
url:              #
signoff:          Charles
#disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
#facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
#google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.
include:
  - .well-known
links:
  # - name:         About
  #   url:          /about
  - name:         Blog
    url:          /index.html
  - name:         En
    url:          /en
  - name:         Email
    url:          mailto:dodoinblue@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/dodoinblue
    external:     true
highlighter:      rouge
permalink:        pretty
markdown:         kramdown # redcarpet is no longer supported.
kramdown:
  input: GFM
  hard_wrap: false